version: 0.1.0
name: Task Board Documentation
title: Task Board Documentation
description: This is an detailed docuemntation for the Task Board plugin of Obsidian.
repository: https://github.com/tu2-atmanand/Task-Board-Docs
github_username: tu2-atmanand
site_branch: main
remote_theme: pages-themes/architect@v0.2.0

# Email and twitter are optional:
email: sanketgauns8@gmail.com
twitter_username: tu2-atmanand

plugins:
    - jekyll-relative-links
    - jekyll-remote-theme
relative_links:
    enabled: true
    collections: true
include:
    - README.md
    - 01-Installation.md
    - 02-GettingStarted.md
