remote_theme: pages-themes/slate@v0.2.0
plugins:
    - jekyll-remote-theme
    - jekyll-relative-links
  relative_links:
    enabled: true
    collections: true
  include:
    - README.md
    - 01-Installation.md
    - 02-GettingStarted.md